BookStore/Controllers/AuthorsController.cs
using Dapper;
using Entity_Layer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;

namespace BookStore.Controllers
{
	public class AuthorsController : Controller
	{
		private readonly String connectionString;
		public AuthorsController(IConfiguration config)
		{
			connectionString = config.GetConnectionString("DefaultConnection");
		}
		
		public ActionResult Index()
		{
			
			return View();
		}

		
		public List<Authors> GetAllAuthors()
		{
			
			List<Authors> data;
			using (IDbConnection db = getConnection())
			{
				string _query = @"Select * From Authors a LEFT JOIN
					(Select bookAuthorID as authorID,COUNT(*) as countBook FROM Books 
					GROUP BY bookAuthorID) b ON a.authorID = b.authorID ";
				data = db.Query<Authors>(_query).ToList();
			}
			return data;
		}

		public List<Books> GetBooks(int id)
		{
			List<Books> books = new List<Books>();
            if (id != null)
            {
				using (IDbConnection db = getConnection())
				{
					string _query = "Select * From Books WHERE bookAuthorID=@id";
					books = db.Query<Books>(_query, new {id= id }).ToList();
				}

			}
			return books;
		}
		


		
		[HttpPost]
		public ActionResult Create(Authors p)
		{
			string _query = "INSERT INTO Authors VALUES(@authorName,@authorBday)";
			try
			{
				using (IDbConnection connection = getConnection())
				{
					connection.Execute(_query,p);
				}
					return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}


		
		[HttpPost]
		public ActionResult Edit(Authors p)
		{
			string _query = "UPDATE Authors SET authorName=@authorName, authorBday=@authorBday WHERE authorID=@authorID";
			try
			{
				using (IDbConnection connection = getConnection())
				{

					connection.Execute(_query,p);
				}
					
				return RedirectToAction("Index");
			}
			catch
			{
				return RedirectToAction("Index");
			}
		}

		[HttpPost]
		public void Delete(int id)
		{
			List<Books> books;
			using (IDbConnection connection = getConnection())
			{
				
				string deleteQuery = "DELETE FROM Authors WHERE authorID=@id";
				connection.Execute(deleteQuery,new {id=id});
					
				
			}
		}


		public IDbConnection getConnection()
		{
			IDbConnection temp = new SqlConnection(connectionString);
			return temp;
		}
	}
}

BookStore/Controllers/BooksController.cs
using Dapper;
using Entity_Layer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Nancy.Json;
using System.Data;
using System.Data.SqlClient;


namespace BookStore.Controllers
{
	public class BooksController : Controller
	{
		private readonly String connectionString;
		public BooksController(IConfiguration config)
		{
			connectionString = config.GetConnectionString("DefaultConnection");
		}
		
		public ActionResult Index()
		{
			
			return View();
		}

		[HttpPost]
		public List<Books> GetAllBooks(Filter filter)
        {
			

			int? max, min;
			if (filter.maxPrice != null) max = filter.maxPrice;
			else max = -1;
			if (filter.minPrice != null) min = filter.minPrice;
			else min = -1;


			int[] categories = filter.categoryIDs;
			List<Books> books;

			var sql = @" SELECT DISTINCT b.[bookID],b.[bookName],b.[bookPages],b.[bookPrice],b.[bookAuthorID], a.[authorName], a.[authorID],
						(select STUFF (
							( SELECT ','+c.categoryName FROM BookCategories bc 
							  JOIN Categories c ON bc.categoryID = c.categoryID 
							  WHERE bc.bookID = b.bookID FOR XML PATH('')),1,1,'')
						) as categoryNames 
						FROM [Books] b LEFT JOIN Authors a ON b.bookAuthorID = a.authorID 
					    LEFT JOIN BookCategories bcc ON bcc.bookID = b.bookID WHERE 1=1 ";
			if (max != -1)
			{
				sql += " AND [bookPrice]<=@max ";
			}
			if (min != -1)
			{
				sql += " AND [bookPrice]>=@min ";
			}
			if (categories != null && categories.Any())
			{
				sql += " AND bcc.[categoryID] IN @categories ";
			}


			
			using (IDbConnection db = getConnection())
			{

				books = db.Query<Books>(sql, new {max= max, min=min,categories= categories }).ToList();
				
			}
			return books;
		}


		     
		
		public List<Categories> getCategories()
		{
			List<Categories> categories;
			string _query = "SELECT * FROM Categories";
			using (IDbConnection connection = getConnection())
			{

				categories = connection.Query<Categories>(_query).ToList();

			}
			return categories;


		}

		public int[] getBookCategories(int id)
		{
			List<BookCategories> bCategories;
			int[] _categories;
			string _query = "SELECT * FROM BookCategories WHERE bookID=@id";
			using (IDbConnection connection = getConnection())
			{

				bCategories = connection.Query<BookCategories>(_query, new {id=id}).ToList();

			}
			_categories = bCategories.Select(x => x.categoryID).ToArray();
			return _categories;


		}
		public List<Authors> getAuthors()
		{
			List<Authors> authors;
			string _query = "SELECT * FROM Authors";
			using (IDbConnection connection = getConnection())
			{

				authors = connection.Query<Authors>(_query).ToList();

			}
			return authors;


		}

		[HttpPost]
		public ActionResult Create(Books b)
		{
			
			string addBookQuery = @"INSERT INTO Books (bookName,bookPages,bookPrice,bookAuthorID) 
								  VALUES (@bookName,@bookPages,@bookPrice,@authorID);SELECT @@Identity";
			
			try
			{
				int newID;
				using (IDbConnection connection = getConnection())
				{
					newID = connection.Query<int>(addBookQuery,b).SingleOrDefault();
					string _query = @"INSERT INTO BookCategories (categoryID,bookID) 
									VALUES (@catID,@bookID)";
					if (b.categoryIDs != null)
					{
						foreach (var item in b.categoryIDs)
						{
							connection.Execute(_query, new { catID = item, bookID = newID });
						}
					}
					
					
				}
					return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
		
		


		
		[HttpPost]
		public void Edit(Books p)
		{
			string _queryUPDATE = "UPDATE Books SET bookName=@bookName, bookPages=@bookPages, bookPrice=@bookPrice, bookAuthorID=@authorID WHERE bookID=@bookID";
			string _queryDropCats = "DELETE FROM BookCategories WHERE bookId=@bookID";
			
			try
			{
				
				using(IDbConnection connection = getConnection())
				{
					connection.Execute(_queryUPDATE,p);
					connection.Execute(_queryDropCats,p);
					if(p.categoryIDs != null)
					{
						foreach (var item in p.categoryIDs)
						{
							connection.Execute("INSERT INTO BookCategories(categoryID, bookID) VALUES(@catID,@bookID)", new { catID = item, bookID = p.bookID });
						}
					}
					

				}
				
			}

			catch
			{
				Console.WriteLine("Book editleme hatası");
			}
		}


		
		public ActionResult Delete(int id)
		{
			string _categoryQuery = "DELETE FROM BookCategories WHERE bookID=" + id;
			string _query = "DELETE FROM Books WHERE bookID=" + id;
			using (IDbConnection connection = getConnection())
			{
				int _rows = connection.Execute(_categoryQuery);
				int rows = connection.Execute(_query);
			}
			return RedirectToAction(nameof(Index));
		}

		public IDbConnection getConnection()
		{
			IDbConnection temp = new SqlConnection(connectionString);
			return temp;
		}
	}
}

BookStore/Controllers/CategoriesController.cs
using Dapper;
using Entity_Layer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;

namespace BookStore.Controllers
{
	public class CategoriesController : Controller
	{
		private readonly string connectionString;
		public CategoriesController(IConfiguration config)
		{
			connectionString = config.GetConnectionString("DefaultConnection");
		}
		
		public ActionResult Index()
		{
			List<Categories> categories;
			using (IDbConnection db = getConnection())
			{
				string _query = "Select * From Categories";
				categories = db.Query<Categories>(_query).ToList();
			}
			return View(categories);
		}

		public List<Categories> GetAllCategories()
        {
			List<Categories> categories;
			using (IDbConnection db = getConnection())
			{
				string _query = "Select * From Categories";
				categories = db.Query<Categories>(_query).ToList();
			}
			return categories;
		}

		public ActionResult ShowBooks(int id)
		{
			List<Books> books;
			using (IDbConnection connection = getConnection())
			{
				
				string _query = @"Select * FROM BookCategories a 
				LEFT JOIN (Select [bookName],[bookID],[bookPages],[bookPrice] From Books) b 
				ON a.bookID=b.bookID WHERE categoryID=@id";
				books = connection.Query<Books>(_query,new {id=id}).ToList();
			}

			return View(books);
		}
		public ActionResult PartialShowBooks(int id)
		{
			List<Books> books = GetCategoryBooks(id);
			return PartialView(books);
		}
		public List<Books> GetCategoryBooks(int? id)
		{
			List<Books> books = new List<Books>();
            if (id != null)
            {

				using (IDbConnection connection = getConnection())
				{
					
					string _query = @"Select * FROM [BookCategories] a 
									LEFT JOIN (Select * From [Books] c LEFT JOIN [Authors] d ON c.[bookAuthorID] = d.[authorID]) b 
									ON a.[bookID]=b.[bookID] WHERE [categoryID]=@id";
					books = connection.Query<Books>(_query,new {id=id}).ToList();
				}
            }

			return books;
		}


		public IDbConnection getConnection()
		{
			IDbConnection temp = new SqlConnection(connectionString);
			return temp;
		}

		
		
		[HttpPost]
		public ActionResult Create(Categories c)
		{
			string _query = "INSERT INTO Categories (categoryName) VALUES (@categoryName)";
			try
			{
				using (IDbConnection connection = getConnection())
				{
					
					connection.Execute(_query,c);
				}
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		
		public ActionResult Edit(int id)
		{
			Categories c;
			String _query = "SELECT * FROM Categories WHERE categoryID=@id";
			using(IDbConnection connection = getConnection())
			{
				c = connection.Query<Categories>(_query,new {id=id}).SingleOrDefault();
			}
			return View(c);
		}

		
		[HttpPost]
		public ActionResult Edit(Categories c)
		{
			string _query = "UPDATE Categories SET categoryName=@categoryName WHERE categoryID=@categoryID";
			try
			{
				using (IDbConnection connection = getConnection())
				{
					connection.Execute(_query,c);
				}
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		

		
		[HttpPost]
		public ActionResult Delete(int id)
		{
			string _categoryQuery = "DELETE FROM BookCategories WHERE categoryID=@id";
			string _query = "DELETE FROM Categories WHERE categoryID=@id";
			using (IDbConnection connection = getConnection())
			{
				connection.Execute(_categoryQuery, new {id= id });
				connection.Execute(_query, new { id = id });
			}
			return RedirectToAction(nameof(Index));
		}
	}
}

BookStore/Controllers/ReportsController.cs
using Dapper;
using Entity_Layer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;

namespace BookStore.Controllers
{
	public class ReportsController : Controller
	{
		private readonly string connectionString;
		public ReportsController(IConfiguration config)
		{
			connectionString = config.GetConnectionString("DefaultConnection");
		}

		public IDbConnection getConnection()
		{
			IDbConnection db = new SqlConnection(connectionString);
			return db;
		}
		
		public ActionResult Index()
		{


			return View();
		}

		public List<Categories> GetFirstChart()
		{
			List<Categories> categoriesNumber;
			using (IDbConnection db = getConnection())
			{
				String _query = @"SELECT a.[categoryName],COUNT(*) AS sumCategory 
								FROM Categories a LEFT JOIN [BookCategories] b 
								ON a.[categoryID] = b.[categoryID] 
								GROUP BY a.[categoryName]";
				categoriesNumber = db.Query<Categories>(_query).ToList();
			}
			return categoriesNumber;
		}

		public List<Authors> GetSecondChart()
		{
			List<Authors> a;
			using (IDbConnection db = getConnection())
			{
				String _query = @"SELECT a.[authorName],COUNT(*) AS countBook 
								FROM [Authors] a LEFT JOIN [Books] b 
								ON a.[authorID]=b.[bookAuthorID] 
								GROUP BY a.[authorName]";
				a = db.Query<Authors>(_query).ToList();
			}
			return a;
		}

	}
}

BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookStore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authors" asp-action="Index">Author</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Book</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reports" asp-action="Index">Reports</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BookStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @*DATATABLE*@
    <link href="//cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" rel="stylesheet" />
    <script src="//cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>

    @*SELECTIZE*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.13.3/css/selectize.css" integrity="sha512-85w5tjZHguXpvARsBrIg9NWdNy5UBK16rAL8VWgnWXK2vMtcRKCBsHWSUbmMu0qHfXW2FVUDiWr6crA+IFdd1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.13.3/js/standalone/selectize.js" integrity="sha512-pF+DNRwavWMukUv/LyzDyDMn8U2uvqYQdJN0Zvilr6DDo/56xPDZdDoyPDYZRSL4aOKO/FGKXTpzDyQJ8je8Qw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    @*CHART.JS*@
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>